name: Aduit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  audit:
    env:
      GO111MODULE: on

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with: 
        go-version: 1.17

    - name: Verify dependencies
      run: go mod verify

#    - name: Build
#      run: go build -o hello -v ./... 
#      run: make build

    - name: Run go vet
      run: go vet ./...

    - name: install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...